config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to:"tops#index"
 #resources :tops
 resources :notices
 resources :procedures do
  resources :comments, only: :create  
 end
 resources :calculations, only: [:index] do
  collection do
    get 'bmi'
    get 'gamma'
    get 'drop'
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '基礎看護技術' },
    { id: 3, name: '循環器疾患' },
    { id: 4, name: '消化器疾患' },
    { id: 5, name: '脳・神経疾患' },
    { id: 6, name: '救命救急' },
    { id: 7, name: '外来' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :procedure
  belongs_to :user

  validates :comment, presence: true
end

app/models/hospital_name.rb
class HospitalName < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'おとな病院' },
    { id: 3, name: 'こども病院' },
    { id: 4, name: 'がんセンター' },
    { id: 5, name: 'ハートクリニック' },
    { id: 6, name: 'メンタルクリニック' },
    { id: 7, name: '感染症病院' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true
  validates :text, presence: true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  validates :image, presence: true
  validates :title, presence: true
  validates :text, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  validates :category_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :procedures
  has_many :comments
  has_many :notices
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'must contain both letters and numbers' }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :hospital_name
  validates :hospital_name_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }

  belongs_to :ward
  validates :ward_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/ward.rb
class Ward < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '5階循環器病棟' },
    { id: 3, name: '6階消化器病棟' },
    { id: 4, name: '7階がん病棟' },
    { id: 5, name: '8階外科病棟' },
    { id: 6, name: '9階内科病棟' },
    { id: 7, name: '救命救急センター' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:name, :email, :hospital_name_id, :ward_id])
  end
end

app/controllers/calculations_controller.rb
# app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  def index
  end

  def bmi
  end

  def gamma
  end

  def drop
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @procedure = Procedure.find(params[:procedure_id])
    @comment = @procedure.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to procedure_path(@procedure), notice: 'コメントが投稿されました。'
    else
      redirect_to procedure_path(@procedure), alert: 'コメントの投稿に失敗しました。'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @notices = Notice.order(created_at: :desc)
    return unless current_user

    @hospital_name = current_user.hospital_name
    @ward = current_user.ward
  end

  def show
    @user = @notice.user
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = current_user.notices.build(notice_params)
    if @notice.save
      redirect_to @notice, notice: '手続きが正常に作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @notice.destroy
    redirect_to root_path, notice: '手続きが削除されました。'
  end

  def edit
  end

  def update
    if @notice.update(notice_params)
      redirect_to @notice, notice: '手続きが正常に更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_notice
    @notice = Notice.find(params[:id])
  end

  def notice_params
    params.require(:notice).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @procedures = Procedure.order(created_at: :desc)
    return unless current_user

    @hospital_name = current_user.hospital_name
    @ward = current_user.ward
  end

  def show
    @user = @procedure.user
    @comment = Comment.new
    @comments = @procedure.comments.includes(:user)
  end

  def new
    @procedure = Procedure.new
  end

  def create
    @procedure = current_user.procedures.build(procedure_params)
    if @procedure.save
      redirect_to @procedure, notice: '手続きが正常に作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @procedure.destroy
    redirect_to root_path, notice: '手続きが削除されました。'
  end

  def edit
  end

  def update
    if @procedure.update(procedure_params)
      redirect_to @procedure, notice: '手続きが正常に更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_procedure
    @procedure = Procedure.find(params[:id])
  end

  def procedure_params
    params.require(:procedure).permit(:title, :material, :text, :category_id, :image).merge(user_id: current_user.id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/calculations/bmi.html.erb
<%= render "shared/second-header" %>

<div class="calculation-info">
    <h1>BMI計算ページ</h1>
    <h2>BMIとは</h2>
    <p>BMI（Body Mass Index）は、体重と身長から肥満度を評価するための指数です。<br>体重 (kg) を身長 (m) の2乗で割ることで計算されます。</p><br>
    
    <div class="measures">
        <h3>BMIの判定基準</h3>
        <ul>
            <li>18.5未満: 低体重</li>
            <li>18.5以上25未満: 普通体重</li>
            <li>25以上30未満: 肥満 (1度)</li>
            <li>30以上35未満: 肥満 (2度)</li>
            <li>35以上40未満: 肥満 (3度)</li>
            <li>40以上: 肥満 (4度)</li>
        </ul><br>
    </div>
    
    <form id="calculationForm">
      <h3>身長と体重を入力してください</h3>
        <div class="height">
            <label for="height">身長 (cm):</label>
            <input type="number" id="height" name="height" required>
        </div>
        <div class="weight">
            <label for="weight">体重 (kg):</label>
            <input type="number" id="weight" name="weight" required>
        </div>
        <div>
            <button class="calculate-btn" type="button">計算する</button>
        </div>
    </form>

    <div class="calculation-result">
        <p>BMIは <span id="your-result">結果</span> です。</p>
    </div>

    <div class="calculation-image">
        <%= image_tag "bmi01.png", class: "calculation-pict" %>
        <%= image_tag "bmi02.png", class: "calculation-pict" %>
    </div>
</div>

<%= render "shared/second-footer" %>

app/views/calculations/index.html.erb
<%= render "shared/second-header"%>
<div class="c-index-container">
  <h1>計算ツールの目次</h1>
  <ul>
    <li><%= link_to 'BMI計算', bmi_calculations_path %></li>
    <li><%= link_to 'Gamma計算', gamma_calculations_path %></li>
    <li><%= link_to '点滴の滴下計算', drop_calculations_path %></li>
  </ul>
</div>

<div class="c-index-container-btn">
  <p><%= link_to '登録する', new_procedure_path, class: "c-go-page" %> </p>
  <p><%= link_to 'トップページに戻る', root_path, class: "c-go-page" %> </p>
</div>

<%= render "shared/second-footer"%>

app/views/notice/new.html.erb
<h1><%= link_to "#{current_user.hospital_name.name}", new_user_session_path(current_user), class: "user-name" %> </h1>
<h1><%= link_to "#{current_user.ward.name}", new_user_session_path(current_user), class: "user-name" %> </h1>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('kanpe-logo.png' , size: '50x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">お知らせを入力</h2>
     <%= form_with model: @notice, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <%# お知らせ説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"title", placeholder:"必須: 40文字まで", maxlength:"40" %>
        <div class="items-explain">
        <div class="weight-bold-text">
          お知らせ内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"text", placeholder:"説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# お知らせ説明 %>

     <%# お知らせ画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"procedure-image" %>
      </div>
    </div>
    <%# /お知らせ画像 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        引用文献・参考文献がある場合は記載してください。
      </p>
    </div>
    <%# /注意書き %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', notices_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">カンペ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('kanpe-logo.png' , size: '50x50'), "/" %>
    <p class="inc">
      ©︎KANPE,Inc.
    </p>
  </footer>
</div>

app/views/notices/edit.html.erb
<h1><%= link_to "#{current_user.hospital_name.name}", new_user_session_path(current_user), class: "user-name" %> </h1>
<h1><%= link_to "#{current_user.ward.name}", new_user_session_path(current_user), class: "user-name" %> </h1>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('kanpe-logo.png' , size: '50x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">お知らせを入力</h2>
     <%= form_with model: @notice, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%#= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
   
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"title", placeholder:"必須: 40文字まで", maxlength:"40" %>
        <div class="items-explain">
        <div class="weight-bold-text">
          お知らせ内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"text", placeholder:"説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

     <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"procedure-image" %>
      </div>
    </div>
    <%# /商品画像 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        引用文献・参考文献がある場合は記載してください。
      </p>
    </div>
    <%# /注意書き %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', notices_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">カンペ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('kanpe-logo.png' , size: '50x50'), "/" %>
    <p class="inc">
      ©︎KANPE,Inc.
    </p>
  </footer>
</div>

app/views/notices/index.html.erb
<%= render "shared/second-header"%>

<div class="p-index-container">
  <h1>お知らせ</h1>
  <h2><%= @hospital_name.name %><br><%= @ward.name %></h2>
  <h2>新着</h2>
  <ul>
  <% @notices.each do |notice| %>
       <li>更新日時：<%=link_to  notice.created_at.strftime('%Y年%m月%d日 %H:%M'), notice_path(notice) %><br>タイトル：<%= link_to notice.title, notice_path(notice) %></li>
    <% end %>
</ul>

<div class="p-index-container-btn">
  <p><%= link_to '登録する', new_notice_path, class: "p-go-page" %> </p>
  <p><%= link_to 'トップページに戻る', root_path, class: "p-go-page" %> </p>
</div>

  <%= render "shared/second-footer"%>

app/views/notices/new.html.erb
<h1><%= link_to "#{current_user.hospital_name.name}", new_user_session_path(current_user), class: "user-name" %> </h1>
<h1><%= link_to "#{current_user.ward.name}", new_user_session_path(current_user), class: "user-name" %> </h1>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('kanpe-logo.png' , size: '50x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">お知らせを入力</h2>
     <%= form_with model: @notice, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <%# お知らせ説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"title", placeholder:"必須: 40文字まで", maxlength:"40" %>
        <div class="items-explain">
        <div class="weight-bold-text">
          お知らせ内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"text", placeholder:"説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# お知らせ説明 %>

     <%# お知らせ画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"procedure-image" %>
      </div>
    </div>
    <%# /お知らせ画像 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        引用文献・参考文献がある場合は記載してください。
      </p>
    </div>
    <%# /注意書き %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', notices_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">カンペ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('kanpe-logo.png' , size: '50x50'), "/" %>
    <p class="inc">
      ©︎KANPE,Inc.
    </p>
  </footer>
</div>

app/views/notices/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @notice.title %>
    </h2>
    <div class="item-img-content">
  <% if @notice.image.present? %>
    <%= image_tag @notice.image, class: "item-img" %>
  <% end %>
</div>

    
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">登録日時</th>
          <td class="detail-value"><%= @notice.created_at.strftime('%Y年%m月%d日 %H:%M') %></td>
        </tr><tr>
          <th class="detail-item">記載者</th>
          <td class="detail-value"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">お知らせ内容</th>
          <td class="detail-value"><%= @notice.text %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png", class: "favorite-star-icon", width: "20", height: "20" %>
        <span>読みました 0</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <% if user_signed_in? %>
    <% if current_user == @notice.user %>
      <%= link_to "編集", edit_notice_path(@notice), method: :get, class: "item-red-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", notice_path(@notice), data: { turbo_method: :delete }, class: "item-red-btn" %>
    <% else %>
      <%= link_to 'もどる', root_path, class: "procedure-destroy" %>
    <% end %>
  <% end %>

  <%# 下部ボタン %>
    <p><%= link_to '一覧に戻る', notices_path, class: "p-go-page" %> </p>
    <%# /下部ボタン %>

    </div>
  </div>

  <div class="another-item"><%=link_to 'お知らせをもっと見る', notices_path, class:"another-item" %></div>

</div>

<%= render "shared/footer" %>

app/views/procedures/index.html.erb
<%= render "shared/second-header"%>

<div class="p-index-container">
  <h1>基準・手順</h1>
  <h2><%= @hospital_name.name %><br><%= @ward.name %></h2>
  <h2>目次</h2>
  <ul>
    <% @procedures.each do |procedure| %>
      <li><%= link_to procedure.title, procedure_path(procedure) %></li>
    <% end %>
  </ul>
</div>

<div class="p-index-container-btn">
  <p><%= link_to '登録する', new_procedure_path, class: "p-go-page" %> </p>
  <p><%= link_to 'トップページに戻る', root_path, class: "p-go-page" %> </p>
</div>



  <%= render "shared/second-footer"%>

app/views/procedures/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @procedure.title %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @procedure.image, class: "item-img" %>
    </div>
    
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">記載者</th>
          <td class="detail-value"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @procedure.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">必要物品</th>
          <td class="detail-value"><%= @procedure.material %></td>
        </tr>
        <tr>
          <th class="detail-item">基準・手順</th>
          <td class="detail-value"><%= @procedure.text %></td>
        </tr>
        <tr>
           <th class="detail-item">コメント一覧</th>
      <td class="detail-value"<% @comments.each do |comment| %>
  <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
  <%= comment.comment %>
</p>
      <% end %></td>
      </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png", class: "favorite-star-icon", width: "20", height: "20" %>
        <span>読みました 0</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <% if user_signed_in? %>
    <% if current_user == @procedure.user %>
      <%= link_to "編集", edit_procedure_path(@procedure), method: :get, class: "item-red-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", procedure_path(@procedure), data: { turbo_method: :delete }, class: "item-red-btn" %>
    <% else %>
      <%= link_to 'もどる', root_path, class: "procedure-destroy" %>
    <% end %>
  <% end %>

  <div class="comment-box">
    <% if user_signed_in? %>
      <%= form_with(model: [@procedure, @comment], local: true) do |f| %>
  <%= f.text_area :comment, placeholder: "コメントする", rows: "2", class: "comment-text" %>
  <p class="comment-warn">
    相手のことを考え丁寧なコメントを心がけましょう。
    <br>
    不快な言葉遣いなどは利用制限や退会処分となることがあります。
  </p>
  <button type="submit" class="comment-btn">
    <%= image_tag "comment.png", class: "comment-flag-icon", width: "20", height: "25" %>
    <span>コメントする</span>
  </button>
   <% end %>
  <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
  <% end %>
   
    </div>
  </div>
  
 <%= link_to 'もどる', procedures_path, class: "p-go-page" %>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>KANPE利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "kanpe-logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("kanpe-logo.png", class:"second-logo"), "/" %>
</header>

app/views/tops/index.html.erb
<%= render "shared/header" %>
<div class='main'>

<%# 画面上部の帯部分 %>
<div class='title-contents'>
  <div class='title-letters'>
    <h2 class='service-title01'>KANPE</h2>
    <h2 class='service-title02'>カンペ</h2>
    <p class='service-explain'>看護師の仕事効率をあげる便利ツールです★</p>
  </div>
  <div class='title-image'>
    <p class='main-image'>
      <%= link_to image_tag("top-header01.png") %>
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class: "apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class: "google-btn"), "#" %>
    </div>
  </div>
</div>
<%# /画面上部の帯部分 %>

  <%# 3つの理由部分 %>

  <div class='select-reason-contents'>
    <h2 class='title'>
      KANPE(カンペ)でできること
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "top-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>基準手順</span>
          を仲間と共有
        </h3>
        <p class='reason-list-description'>
          周知伝達の時間短縮！
        </p>
        <% if user_signed_in? %>
        <p><%= link_to 'GO!', procedures_path, class: "go-page" %> </p>
        <% end %>
      </li>
      <li class='list'>
        <%= image_tag "top-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>ラクラク計算ツール</span>
          ですぐに計算
        </h3>
        <p class='reason-list-description'>
          滴下計算もガンマ計算もこれですぐ算出！
        </p><br>
        <% if user_signed_in? %>
        <p><%= link_to 'GO!', calculations_path, class: "go-page" %> </p>
        <% end %>
      </li>

      <li class='list'>
        <%= image_tag "top-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>病棟のお知らせ共有</span>
        </h3>
        <p class='reason-list-description'>
          もう連絡ノートの取り合いは無くなるはず！
        </p>
        <% if user_signed_in? %>
        <p><%= link_to 'GO!', notices_path, class: "go-page" %> </p>
        <% end %>
   
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>


</div>
<% unless user_signed_in? %>ｖ
<%= link_to(new_user_registration_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>新規登録する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<% end %>
<%= render "shared/footer" %>